import { Product } from "@/types/product";

// Simulação de banco de dados em memória compartilhado
export let products: Product[] = [
  {
    id: "1",
    name: "Smartphone XYZ",
    description:
      "Smartphone moderno com excelente desempenho e câmera de alta qualidade",
    price: 999.99,
    category: "Eletrônicos",
    inStock: true,
    tags: ["Novo", "Premium"],
    rating: 4,
    releaseDate: new Date().toISOString(),
    color: "black",
    size: "M",
    weight: 0.2,
    isFragile: true,
    priority: "high",
    supplier: "Fornecedor A",
    notes: "Produto de alta qualidade",
    images: [
      "https://images.pexels.com/photos/404280/pexels-photo-404280.jpeg",
    ],
    discount: 10,
    featured: true,
    status: "active",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Notebook Pro",
    description: "Notebook profissional para desenvolvimento e design",
    price: 2499.99,
    category: "Computadores",
    inStock: false,
    tags: ["Bestseller", "Profissional"],
    rating: 5,
    releaseDate: new Date().toISOString(),
    color: "gray",
    size: "G",
    weight: 2.5,
    isFragile: true,
    priority: "medium",
    supplier: "Fornecedor B",
    notes: "Ideal para profissionais",
    images: ["https://images.pexels.com/photos/18105/pexels-photo.jpg"],
    discount: 0,
    featured: false,
    status: "inactive",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
